# Generated by Django 4.2.30 on 2026-07-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsinfo',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='projectsinfo',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='projectsinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
