# Generated by Django 4.2.30 on 2026-07-18 17:30

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectsinfo_options_projectsinfo_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.project_image_path),
        ),
    ]
