# Generated by Django 6.0.6 on 2026-06-07 15:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvcourses',
            options={'ordering': ['date'], 'verbose_name': '06. CVCourses', 'verbose_name_plural': '06. CVCourses'},
        ),
        migrations.AlterModelOptions(
            name='cveducation',
            options={'ordering': ['date_end'], 'verbose_name': '05. CVEducation', 'verbose_name_plural': '05. CVEducations'},
        ),
        migrations.AlterModelOptions(
            name='cvexperience',
            options={'ordering': ['date_end'], 'verbose_name': '03. CVExperience', 'verbose_name_plural': '03. CVExperiences'},
        ),
        migrations.AlterModelOptions(
            name='cvpetproject',
            options={'ordering': ['date'], 'verbose_name': '04. CVPetProject', 'verbose_name_plural': '04. CVPetProjects'},
        ),
        migrations.AlterModelOptions(
            name='cvprofile',
            options={'verbose_name': '01. CVProfile', 'verbose_name_plural': '01. CVProfiles'},
        ),
        migrations.AlterModelOptions(
            name='cvskill',
            options={'ordering': ['-date_added'], 'verbose_name': '02. CVSkill', 'verbose_name_plural': '02. CVSkills'},
        ),
        migrations.AddField(
            model_name='cvskill',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
