# Generated by Django 4.2.30 on 2026-06-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cvcourses_options_alter_cveducation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvcourses',
            options={'ordering': ['-date'], 'verbose_name': '06. CVCourses', 'verbose_name_plural': '06. CVCourses'},
        ),
        migrations.AlterModelOptions(
            name='cvpetproject',
            options={'ordering': ['-date'], 'verbose_name': '04. CVPetProject', 'verbose_name_plural': '04. CVPetProjects'},
        ),
        migrations.AlterField(
            model_name='cvcourses',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cveducation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cvexperience',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cvpetproject',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cvprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cvskill',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
