# Generated by Django 4.2.30 on 2026-07-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cvcourses_id_alter_cveducation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvpetproject',
            name='technology_stack',
            field=models.TextField(max_length=1500),
        ),
    ]
